-- =====================================================================
--  Football Genius — Supabase Player Data Schema
--  Run this in your Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- =====================================================================

-- ─── Table 1: global_players (Higher/Lower game) ────────────────────
CREATE TABLE IF NOT EXISTS global_players (
  id TEXT PRIMARY KEY,                    -- e.g. "messi"
  name TEXT NOT NULL,
  image TEXT NOT NULL,                    -- relative path e.g. "img/players/messi.jpg"
  career_goals INTEGER NOT NULL DEFAULT 0,
  career_trophies INTEGER NOT NULL DEFAULT 0,
  market_value NUMERIC NOT NULL DEFAULT 0,        -- USD millions
  transfer_from TEXT,
  transfer_to TEXT,
  transfer_fee NUMERIC NOT NULL DEFAULT 0,        -- USD millions
  transfermarkt_id INTEGER,              -- for automated scraping
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Table 2: guess_players (Guess Who game) ────────────────────────
CREATE TABLE IF NOT EXISTS guess_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  image TEXT NOT NULL,
  club TEXT NOT NULL,
  nation TEXT NOT NULL,
  transfermarkt_id INTEGER,              -- for automated scraping
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Table 3: grid_players (Grid Challenge game) ────────────────────
CREATE TABLE IF NOT EXISTS grid_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  clubs TEXT[] NOT NULL DEFAULT '{}',     -- PostgreSQL text array
  nation TEXT NOT NULL,
  stats TEXT[] NOT NULL DEFAULT '{}',     -- PostgreSQL array of stat IDs
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- App tables used by auth, dashboard, and leaderboard
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT profiles_username_length
    CHECK (username IS NULL OR char_length(trim(username)) BETWEEN 1 AND 32)
);

CREATE TABLE IF NOT EXISTS scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  mode TEXT NOT NULL,
  score INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT scores_mode_check
    CHECK (mode IN ('scoreline', 'unscramble', 'whosaidit', 'higherlower', 'grid', 'transfer', 'guess')),
  CONSTRAINT scores_score_check
    CHECK (score >= 0 AND score <= 1000)
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON profiles;
CREATE TRIGGER set_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ─── Row Level Security ─────────────────────────────────────────────
ALTER TABLE global_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE guess_players  ENABLE ROW LEVEL SECURITY;
ALTER TABLE grid_players   ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles       ENABLE ROW LEVEL SECURITY;
ALTER TABLE scores         ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read global_players" ON global_players;
DROP POLICY IF EXISTS "Public read guess_players" ON guess_players;
DROP POLICY IF EXISTS "Public read grid_players" ON grid_players;
DROP POLICY IF EXISTS "Service write global_players" ON global_players;
DROP POLICY IF EXISTS "Service write guess_players" ON guess_players;
DROP POLICY IF EXISTS "Service write grid_players" ON grid_players;
DROP POLICY IF EXISTS "Public read profiles" ON profiles;
DROP POLICY IF EXISTS "Users insert own profile" ON profiles;
DROP POLICY IF EXISTS "Users update own profile" ON profiles;
DROP POLICY IF EXISTS "Public read scores" ON scores;
DROP POLICY IF EXISTS "Users insert own scores" ON scores;

-- Public read access (anyone with the anon key can SELECT)
CREATE POLICY "Public read global_players" ON global_players FOR SELECT USING (true);
CREATE POLICY "Public read guess_players"  ON guess_players  FOR SELECT USING (true);
CREATE POLICY "Public read grid_players"   ON grid_players   FOR SELECT USING (true);
CREATE POLICY "Public read profiles"       ON profiles       FOR SELECT USING (true);
CREATE POLICY "Users insert own profile"   ON profiles       FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile"   ON profiles       FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Public read scores"         ON scores         FOR SELECT USING (true);
CREATE POLICY "Users insert own scores"    ON scores         FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Service role can do everything (used by the automated updater)
-- (Service role bypasses RLS by default, but explicit policies for clarity)
-- Do not add public write policies here.
-- Supabase's service_role bypasses RLS automatically for trusted server jobs.

-- ─── Indexes for performance ────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_guess_players_name ON guess_players(name);
CREATE INDEX IF NOT EXISTS idx_grid_players_name  ON grid_players(name);
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
CREATE INDEX IF NOT EXISTS idx_scores_user_id_created_at ON scores(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scores_mode_created_at ON scores(mode, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scores_mode_score ON scores(mode, score DESC);

CREATE OR REPLACE FUNCTION get_leaderboard(
  p_mode TEXT DEFAULT NULL,
  p_period TEXT DEFAULT 'all',
  p_limit INTEGER DEFAULT 50
)
RETURNS TABLE (
  rank BIGINT,
  user_id UUID,
  username TEXT,
  avatar_url TEXT,
  best_score INTEGER,
  games_played BIGINT
)
LANGUAGE sql
STABLE
AS $$
  WITH filtered_scores AS (
    SELECT s.user_id, s.score, s.created_at
    FROM scores s
    WHERE (p_mode IS NULL OR s.mode = p_mode)
      AND (
        p_period = 'all'
        OR (p_period = 'daily' AND s.created_at >= now() - interval '1 day')
        OR (p_period = 'weekly' AND s.created_at >= now() - interval '7 days')
      )
  ),
  aggregated AS (
    SELECT
      fs.user_id,
      MAX(fs.score)::INTEGER AS best_score,
      COUNT(*)::BIGINT AS games_played
    FROM filtered_scores fs
    GROUP BY fs.user_id
  ),
  ranked AS (
    SELECT
      ROW_NUMBER() OVER (ORDER BY a.best_score DESC, a.games_played DESC, a.user_id) AS rank,
      a.user_id,
      p.username,
      p.avatar_url,
      a.best_score,
      a.games_played
    FROM aggregated a
    LEFT JOIN profiles p ON p.id = a.user_id
  )
  SELECT
    r.rank,
    r.user_id,
    r.username,
    r.avatar_url,
    r.best_score,
    r.games_played
  FROM ranked r
  ORDER BY r.rank
  LIMIT GREATEST(COALESCE(p_limit, 50), 1);
$$;
